/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TribesIndexRouteImport } from './routes/tribes.index'
import { Route as OfficesIndexRouteImport } from './routes/offices.index'
import { Route as TribesSlugRouteImport } from './routes/tribes.$slug'
import { Route as PersonsIdRouteImport } from './routes/persons.$id'
import { Route as OfficesSlugRouteImport } from './routes/offices.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TribesIndexRoute = TribesIndexRouteImport.update({
  id: '/tribes/',
  path: '/tribes/',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficesIndexRoute = OfficesIndexRouteImport.update({
  id: '/offices/',
  path: '/offices/',
  getParentRoute: () => rootRouteImport,
} as any)
const TribesSlugRoute = TribesSlugRouteImport.update({
  id: '/tribes/$slug',
  path: '/tribes/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonsIdRoute = PersonsIdRouteImport.update({
  id: '/persons/$id',
  path: '/persons/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficesSlugRoute = OfficesSlugRouteImport.update({
  id: '/offices/$slug',
  path: '/offices/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/offices/$slug': typeof OfficesSlugRoute
  '/persons/$id': typeof PersonsIdRoute
  '/tribes/$slug': typeof TribesSlugRoute
  '/offices/': typeof OfficesIndexRoute
  '/tribes/': typeof TribesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/offices/$slug': typeof OfficesSlugRoute
  '/persons/$id': typeof PersonsIdRoute
  '/tribes/$slug': typeof TribesSlugRoute
  '/offices': typeof OfficesIndexRoute
  '/tribes': typeof TribesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/offices/$slug': typeof OfficesSlugRoute
  '/persons/$id': typeof PersonsIdRoute
  '/tribes/$slug': typeof TribesSlugRoute
  '/offices/': typeof OfficesIndexRoute
  '/tribes/': typeof TribesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/offices/$slug'
    | '/persons/$id'
    | '/tribes/$slug'
    | '/offices/'
    | '/tribes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/offices/$slug'
    | '/persons/$id'
    | '/tribes/$slug'
    | '/offices'
    | '/tribes'
  id:
    | '__root__'
    | '/'
    | '/offices/$slug'
    | '/persons/$id'
    | '/tribes/$slug'
    | '/offices/'
    | '/tribes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OfficesSlugRoute: typeof OfficesSlugRoute
  PersonsIdRoute: typeof PersonsIdRoute
  TribesSlugRoute: typeof TribesSlugRoute
  OfficesIndexRoute: typeof OfficesIndexRoute
  TribesIndexRoute: typeof TribesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tribes/': {
      id: '/tribes/'
      path: '/tribes'
      fullPath: '/tribes/'
      preLoaderRoute: typeof TribesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offices/': {
      id: '/offices/'
      path: '/offices'
      fullPath: '/offices/'
      preLoaderRoute: typeof OfficesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tribes/$slug': {
      id: '/tribes/$slug'
      path: '/tribes/$slug'
      fullPath: '/tribes/$slug'
      preLoaderRoute: typeof TribesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/persons/$id': {
      id: '/persons/$id'
      path: '/persons/$id'
      fullPath: '/persons/$id'
      preLoaderRoute: typeof PersonsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offices/$slug': {
      id: '/offices/$slug'
      path: '/offices/$slug'
      fullPath: '/offices/$slug'
      preLoaderRoute: typeof OfficesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OfficesSlugRoute: OfficesSlugRoute,
  PersonsIdRoute: PersonsIdRoute,
  TribesSlugRoute: TribesSlugRoute,
  OfficesIndexRoute: OfficesIndexRoute,
  TribesIndexRoute: TribesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
