/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as DirectoryRouteImport } from './routes/directory'
import { Route as GentesIndexRouteImport } from './routes/gentes.index'
import { Route as GentesSlugRouteImport } from './routes/gentes.$slug'
import { Route as OfficesIndexRouteImport } from './routes/offices.index'
import { Route as OfficesSlugRouteImport } from './routes/offices.$slug'
import { Route as PersonsIdRouteImport } from './routes/persons.$id'
import { Route as ProvincesIndexRouteImport } from './routes/provinces.index'
import { Route as ProvincesSlugRouteImport } from './routes/provinces.$slug'
import { Route as TribesIndexRouteImport } from './routes/tribes.index'
import { Route as TribesSlugRouteImport } from './routes/tribes.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const DirectoryRoute = DirectoryRouteImport.update({
  id: '/directory',
  path: '/directory',
  getParentRoute: () => rootRouteImport,
} as any)
const GentesIndexRoute = GentesIndexRouteImport.update({
  id: '/gentes/',
  path: '/gentes/',
  getParentRoute: () => rootRouteImport,
} as any)
const GentesSlugRoute = GentesSlugRouteImport.update({
  id: '/gentes/$slug',
  path: '/gentes/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficesIndexRoute = OfficesIndexRouteImport.update({
  id: '/offices/',
  path: '/offices/',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficesSlugRoute = OfficesSlugRouteImport.update({
  id: '/offices/$slug',
  path: '/offices/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonsIdRoute = PersonsIdRouteImport.update({
  id: '/persons/$id',
  path: '/persons/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProvincesIndexRoute = ProvincesIndexRouteImport.update({
  id: '/provinces/',
  path: '/provinces/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProvincesSlugRoute = ProvincesSlugRouteImport.update({
  id: '/provinces/$slug',
  path: '/provinces/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const TribesIndexRoute = TribesIndexRouteImport.update({
  id: '/tribes/',
  path: '/tribes/',
  getParentRoute: () => rootRouteImport,
} as any)
const TribesSlugRoute = TribesSlugRouteImport.update({
  id: '/tribes/$slug',
  path: '/tribes/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/directory': typeof DirectoryRoute
  '/gentes/$slug': typeof GentesSlugRoute
  '/offices/$slug': typeof OfficesSlugRoute
  '/persons/$id': typeof PersonsIdRoute
  '/provinces/$slug': typeof ProvincesSlugRoute
  '/tribes/$slug': typeof TribesSlugRoute
  '/gentes/': typeof GentesIndexRoute
  '/offices/': typeof OfficesIndexRoute
  '/provinces/': typeof ProvincesIndexRoute
  '/tribes/': typeof TribesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/directory': typeof DirectoryRoute
  '/gentes/$slug': typeof GentesSlugRoute
  '/offices/$slug': typeof OfficesSlugRoute
  '/persons/$id': typeof PersonsIdRoute
  '/provinces/$slug': typeof ProvincesSlugRoute
  '/tribes/$slug': typeof TribesSlugRoute
  '/gentes': typeof GentesIndexRoute
  '/offices': typeof OfficesIndexRoute
  '/provinces': typeof ProvincesIndexRoute
  '/tribes': typeof TribesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/directory': typeof DirectoryRoute
  '/gentes/$slug': typeof GentesSlugRoute
  '/offices/$slug': typeof OfficesSlugRoute
  '/persons/$id': typeof PersonsIdRoute
  '/provinces/$slug': typeof ProvincesSlugRoute
  '/tribes/$slug': typeof TribesSlugRoute
  '/gentes/': typeof GentesIndexRoute
  '/offices/': typeof OfficesIndexRoute
  '/provinces/': typeof ProvincesIndexRoute
  '/tribes/': typeof TribesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/directory'
    | '/gentes/$slug'
    | '/offices/$slug'
    | '/persons/$id'
    | '/provinces/$slug'
    | '/tribes/$slug'
    | '/gentes/'
    | '/offices/'
    | '/provinces/'
    | '/tribes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/directory'
    | '/gentes/$slug'
    | '/offices/$slug'
    | '/persons/$id'
    | '/provinces/$slug'
    | '/tribes/$slug'
    | '/gentes'
    | '/offices'
    | '/provinces'
    | '/tribes'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/directory'
    | '/gentes/$slug'
    | '/offices/$slug'
    | '/persons/$id'
    | '/provinces/$slug'
    | '/tribes/$slug'
    | '/gentes/'
    | '/offices/'
    | '/provinces/'
    | '/tribes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  DirectoryRoute: typeof DirectoryRoute
  GentesSlugRoute: typeof GentesSlugRoute
  OfficesSlugRoute: typeof OfficesSlugRoute
  PersonsIdRoute: typeof PersonsIdRoute
  ProvincesSlugRoute: typeof ProvincesSlugRoute
  TribesSlugRoute: typeof TribesSlugRoute
  GentesIndexRoute: typeof GentesIndexRoute
  OfficesIndexRoute: typeof OfficesIndexRoute
  ProvincesIndexRoute: typeof ProvincesIndexRoute
  TribesIndexRoute: typeof TribesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/directory': {
      id: '/directory'
      path: '/directory'
      fullPath: '/directory'
      preLoaderRoute: typeof DirectoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gentes/': {
      id: '/gentes/'
      path: '/gentes'
      fullPath: '/gentes/'
      preLoaderRoute: typeof GentesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gentes/$slug': {
      id: '/gentes/$slug'
      path: '/gentes/$slug'
      fullPath: '/gentes/$slug'
      preLoaderRoute: typeof GentesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offices/': {
      id: '/offices/'
      path: '/offices'
      fullPath: '/offices/'
      preLoaderRoute: typeof OfficesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offices/$slug': {
      id: '/offices/$slug'
      path: '/offices/$slug'
      fullPath: '/offices/$slug'
      preLoaderRoute: typeof OfficesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/persons/$id': {
      id: '/persons/$id'
      path: '/persons/$id'
      fullPath: '/persons/$id'
      preLoaderRoute: typeof PersonsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/provinces/': {
      id: '/provinces/'
      path: '/provinces'
      fullPath: '/provinces/'
      preLoaderRoute: typeof ProvincesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/provinces/$slug': {
      id: '/provinces/$slug'
      path: '/provinces/$slug'
      fullPath: '/provinces/$slug'
      preLoaderRoute: typeof ProvincesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tribes/': {
      id: '/tribes/'
      path: '/tribes'
      fullPath: '/tribes/'
      preLoaderRoute: typeof TribesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tribes/$slug': {
      id: '/tribes/$slug'
      path: '/tribes/$slug'
      fullPath: '/tribes/$slug'
      preLoaderRoute: typeof TribesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  DirectoryRoute: DirectoryRoute,
  GentesSlugRoute: GentesSlugRoute,
  OfficesSlugRoute: OfficesSlugRoute,
  PersonsIdRoute: PersonsIdRoute,
  ProvincesSlugRoute: ProvincesSlugRoute,
  TribesSlugRoute: TribesSlugRoute,
  GentesIndexRoute: GentesIndexRoute,
  OfficesIndexRoute: OfficesIndexRoute,
  ProvincesIndexRoute: ProvincesIndexRoute,
  TribesIndexRoute: TribesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
