/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as DirectoryRouteImport } from './routes/directory'
import { Route as SparqlRouteImport } from './routes/sparql'
import { Route as GentesIndexRouteImport } from './routes/gentes.index'
import { Route as GentesSlugRouteImport } from './routes/gentes.$slug'
import { Route as OfficesIndexRouteImport } from './routes/offices.index'
import { Route as OfficesSlugRouteImport } from './routes/offices.$slug'
import { Route as PersonsIdRouteImport } from './routes/persons.$id'
import { Route as PraenominaIndexRouteImport } from './routes/praenomina.index'
import { Route as PraenominaSlugRouteImport } from './routes/praenomina.$slug'
import { Route as ProvincesIndexRouteImport } from './routes/provinces.index'
import { Route as ProvincesSlugRouteImport } from './routes/provinces.$slug'
import { Route as RelationshipsIndexRouteImport } from './routes/relationships.index'
import { Route as RelationshipsSlugRouteImport } from './routes/relationships.$slug'
import { Route as SourcesIndexRouteImport } from './routes/sources.index'
import { Route as SourcesSlugRouteImport } from './routes/sources.$slug'
import { Route as TribesIndexRouteImport } from './routes/tribes.index'
import { Route as TribesSlugRouteImport } from './routes/tribes.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const DirectoryRoute = DirectoryRouteImport.update({
  id: '/directory',
  path: '/directory',
  getParentRoute: () => rootRouteImport,
} as any)
const SparqlRoute = SparqlRouteImport.update({
  id: '/sparql',
  path: '/sparql',
  getParentRoute: () => rootRouteImport,
} as any)
const GentesIndexRoute = GentesIndexRouteImport.update({
  id: '/gentes/',
  path: '/gentes/',
  getParentRoute: () => rootRouteImport,
} as any)
const GentesSlugRoute = GentesSlugRouteImport.update({
  id: '/gentes/$slug',
  path: '/gentes/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficesIndexRoute = OfficesIndexRouteImport.update({
  id: '/offices/',
  path: '/offices/',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficesSlugRoute = OfficesSlugRouteImport.update({
  id: '/offices/$slug',
  path: '/offices/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonsIdRoute = PersonsIdRouteImport.update({
  id: '/persons/$id',
  path: '/persons/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PraenominaIndexRoute = PraenominaIndexRouteImport.update({
  id: '/praenomina/',
  path: '/praenomina/',
  getParentRoute: () => rootRouteImport,
} as any)
const PraenominaSlugRoute = PraenominaSlugRouteImport.update({
  id: '/praenomina/$slug',
  path: '/praenomina/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProvincesIndexRoute = ProvincesIndexRouteImport.update({
  id: '/provinces/',
  path: '/provinces/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProvincesSlugRoute = ProvincesSlugRouteImport.update({
  id: '/provinces/$slug',
  path: '/provinces/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const RelationshipsIndexRoute = RelationshipsIndexRouteImport.update({
  id: '/relationships/',
  path: '/relationships/',
  getParentRoute: () => rootRouteImport,
} as any)
const RelationshipsSlugRoute = RelationshipsSlugRouteImport.update({
  id: '/relationships/$slug',
  path: '/relationships/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SourcesIndexRoute = SourcesIndexRouteImport.update({
  id: '/sources/',
  path: '/sources/',
  getParentRoute: () => rootRouteImport,
} as any)
const SourcesSlugRoute = SourcesSlugRouteImport.update({
  id: '/sources/$slug',
  path: '/sources/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const TribesIndexRoute = TribesIndexRouteImport.update({
  id: '/tribes/',
  path: '/tribes/',
  getParentRoute: () => rootRouteImport,
} as any)
const TribesSlugRoute = TribesSlugRouteImport.update({
  id: '/tribes/$slug',
  path: '/tribes/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/directory': typeof DirectoryRoute
  '/sparql': typeof SparqlRoute
  '/gentes/$slug': typeof GentesSlugRoute
  '/offices/$slug': typeof OfficesSlugRoute
  '/persons/$id': typeof PersonsIdRoute
  '/praenomina/$slug': typeof PraenominaSlugRoute
  '/provinces/$slug': typeof ProvincesSlugRoute
  '/relationships/$slug': typeof RelationshipsSlugRoute
  '/sources/$slug': typeof SourcesSlugRoute
  '/tribes/$slug': typeof TribesSlugRoute
  '/gentes/': typeof GentesIndexRoute
  '/offices/': typeof OfficesIndexRoute
  '/praenomina/': typeof PraenominaIndexRoute
  '/provinces/': typeof ProvincesIndexRoute
  '/relationships/': typeof RelationshipsIndexRoute
  '/sources/': typeof SourcesIndexRoute
  '/tribes/': typeof TribesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/directory': typeof DirectoryRoute
  '/sparql': typeof SparqlRoute
  '/gentes/$slug': typeof GentesSlugRoute
  '/offices/$slug': typeof OfficesSlugRoute
  '/persons/$id': typeof PersonsIdRoute
  '/praenomina/$slug': typeof PraenominaSlugRoute
  '/provinces/$slug': typeof ProvincesSlugRoute
  '/relationships/$slug': typeof RelationshipsSlugRoute
  '/sources/$slug': typeof SourcesSlugRoute
  '/tribes/$slug': typeof TribesSlugRoute
  '/gentes': typeof GentesIndexRoute
  '/offices': typeof OfficesIndexRoute
  '/praenomina': typeof PraenominaIndexRoute
  '/provinces': typeof ProvincesIndexRoute
  '/relationships': typeof RelationshipsIndexRoute
  '/sources': typeof SourcesIndexRoute
  '/tribes': typeof TribesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/directory': typeof DirectoryRoute
  '/sparql': typeof SparqlRoute
  '/gentes/$slug': typeof GentesSlugRoute
  '/offices/$slug': typeof OfficesSlugRoute
  '/persons/$id': typeof PersonsIdRoute
  '/praenomina/$slug': typeof PraenominaSlugRoute
  '/provinces/$slug': typeof ProvincesSlugRoute
  '/relationships/$slug': typeof RelationshipsSlugRoute
  '/sources/$slug': typeof SourcesSlugRoute
  '/tribes/$slug': typeof TribesSlugRoute
  '/gentes/': typeof GentesIndexRoute
  '/offices/': typeof OfficesIndexRoute
  '/praenomina/': typeof PraenominaIndexRoute
  '/provinces/': typeof ProvincesIndexRoute
  '/relationships/': typeof RelationshipsIndexRoute
  '/sources/': typeof SourcesIndexRoute
  '/tribes/': typeof TribesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/directory'
    | '/sparql'
    | '/gentes/$slug'
    | '/offices/$slug'
    | '/persons/$id'
    | '/praenomina/$slug'
    | '/provinces/$slug'
    | '/relationships/$slug'
    | '/sources/$slug'
    | '/tribes/$slug'
    | '/gentes/'
    | '/offices/'
    | '/praenomina/'
    | '/provinces/'
    | '/relationships/'
    | '/sources/'
    | '/tribes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/directory'
    | '/sparql'
    | '/gentes/$slug'
    | '/offices/$slug'
    | '/persons/$id'
    | '/praenomina/$slug'
    | '/provinces/$slug'
    | '/relationships/$slug'
    | '/sources/$slug'
    | '/tribes/$slug'
    | '/gentes'
    | '/offices'
    | '/praenomina'
    | '/provinces'
    | '/relationships'
    | '/sources'
    | '/tribes'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/directory'
    | '/sparql'
    | '/gentes/$slug'
    | '/offices/$slug'
    | '/persons/$id'
    | '/praenomina/$slug'
    | '/provinces/$slug'
    | '/relationships/$slug'
    | '/sources/$slug'
    | '/tribes/$slug'
    | '/gentes/'
    | '/offices/'
    | '/praenomina/'
    | '/provinces/'
    | '/relationships/'
    | '/sources/'
    | '/tribes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  DirectoryRoute: typeof DirectoryRoute
  SparqlRoute: typeof SparqlRoute
  GentesSlugRoute: typeof GentesSlugRoute
  OfficesSlugRoute: typeof OfficesSlugRoute
  PersonsIdRoute: typeof PersonsIdRoute
  PraenominaSlugRoute: typeof PraenominaSlugRoute
  ProvincesSlugRoute: typeof ProvincesSlugRoute
  RelationshipsSlugRoute: typeof RelationshipsSlugRoute
  SourcesSlugRoute: typeof SourcesSlugRoute
  TribesSlugRoute: typeof TribesSlugRoute
  GentesIndexRoute: typeof GentesIndexRoute
  OfficesIndexRoute: typeof OfficesIndexRoute
  PraenominaIndexRoute: typeof PraenominaIndexRoute
  ProvincesIndexRoute: typeof ProvincesIndexRoute
  RelationshipsIndexRoute: typeof RelationshipsIndexRoute
  SourcesIndexRoute: typeof SourcesIndexRoute
  TribesIndexRoute: typeof TribesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/directory': {
      id: '/directory'
      path: '/directory'
      fullPath: '/directory'
      preLoaderRoute: typeof DirectoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sparql': {
      id: '/sparql'
      path: '/sparql'
      fullPath: '/sparql'
      preLoaderRoute: typeof SparqlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gentes/': {
      id: '/gentes/'
      path: '/gentes'
      fullPath: '/gentes/'
      preLoaderRoute: typeof GentesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gentes/$slug': {
      id: '/gentes/$slug'
      path: '/gentes/$slug'
      fullPath: '/gentes/$slug'
      preLoaderRoute: typeof GentesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offices/': {
      id: '/offices/'
      path: '/offices'
      fullPath: '/offices/'
      preLoaderRoute: typeof OfficesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offices/$slug': {
      id: '/offices/$slug'
      path: '/offices/$slug'
      fullPath: '/offices/$slug'
      preLoaderRoute: typeof OfficesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/persons/$id': {
      id: '/persons/$id'
      path: '/persons/$id'
      fullPath: '/persons/$id'
      preLoaderRoute: typeof PersonsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/praenomina/': {
      id: '/praenomina/'
      path: '/praenomina'
      fullPath: '/praenomina/'
      preLoaderRoute: typeof PraenominaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/praenomina/$slug': {
      id: '/praenomina/$slug'
      path: '/praenomina/$slug'
      fullPath: '/praenomina/$slug'
      preLoaderRoute: typeof PraenominaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/provinces/': {
      id: '/provinces/'
      path: '/provinces'
      fullPath: '/provinces/'
      preLoaderRoute: typeof ProvincesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/provinces/$slug': {
      id: '/provinces/$slug'
      path: '/provinces/$slug'
      fullPath: '/provinces/$slug'
      preLoaderRoute: typeof ProvincesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relationships/': {
      id: '/relationships/'
      path: '/relationships'
      fullPath: '/relationships/'
      preLoaderRoute: typeof RelationshipsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relationships/$slug': {
      id: '/relationships/$slug'
      path: '/relationships/$slug'
      fullPath: '/relationships/$slug'
      preLoaderRoute: typeof RelationshipsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sources/': {
      id: '/sources/'
      path: '/sources'
      fullPath: '/sources/'
      preLoaderRoute: typeof SourcesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sources/$slug': {
      id: '/sources/$slug'
      path: '/sources/$slug'
      fullPath: '/sources/$slug'
      preLoaderRoute: typeof SourcesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tribes/': {
      id: '/tribes/'
      path: '/tribes'
      fullPath: '/tribes/'
      preLoaderRoute: typeof TribesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tribes/$slug': {
      id: '/tribes/$slug'
      path: '/tribes/$slug'
      fullPath: '/tribes/$slug'
      preLoaderRoute: typeof TribesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  DirectoryRoute: DirectoryRoute,
  SparqlRoute: SparqlRoute,
  GentesSlugRoute: GentesSlugRoute,
  OfficesSlugRoute: OfficesSlugRoute,
  PersonsIdRoute: PersonsIdRoute,
  PraenominaSlugRoute: PraenominaSlugRoute,
  ProvincesSlugRoute: ProvincesSlugRoute,
  RelationshipsSlugRoute: RelationshipsSlugRoute,
  SourcesSlugRoute: SourcesSlugRoute,
  TribesSlugRoute: TribesSlugRoute,
  GentesIndexRoute: GentesIndexRoute,
  OfficesIndexRoute: OfficesIndexRoute,
  PraenominaIndexRoute: PraenominaIndexRoute,
  ProvincesIndexRoute: ProvincesIndexRoute,
  RelationshipsIndexRoute: RelationshipsIndexRoute,
  SourcesIndexRoute: SourcesIndexRoute,
  TribesIndexRoute: TribesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
